[package]
name = "storage"
version = "0.1.0"
edition = "2024"


[dependencies]
common = { path = "../../common" }
axum.workspace = true
axum-server.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

